# Generated by Django 5.2.8 on 2025-11-07 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_APP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialbalance",
            name="supporting_document",
            field=models.FileField(
                blank=True, null=True, upload_to="supporting_documents/"
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="table_type",
            field=models.CharField(
                choices=[
                    ("trial_balance", "Trial Balance"),
                    ("balance_sheet", "Balance Sheet"),
                ],
                default="trial_balance",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saplink",
            name="status",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="trialbalance",
            name="gl_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("BS_PL", models.CharField(blank=True, max_length=10, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("gl_acct", models.CharField(max_length=20)),
                (
                    "gl_account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("main_head", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_head", models.CharField(blank=True, max_length=100, null=True)),
                ("cml", models.CharField(blank=True, max_length=20, null=True)),
                ("frequency", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "responsible_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "department_spoc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "department_reviewer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("query_type_action_points", models.TextField(blank=True, null=True)),
                ("working_needed", models.TextField(blank=True, null=True)),
                (
                    "confirmation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recon_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "variance_percent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("flag_color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "report_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "analysis_required",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "review_checkpoint_abex",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("fiscal_year", models.CharField(blank=True, max_length=10, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "balance_sheet",
            },
        ),
    ]
